<a href="https://colab.research.google.com/github/JuanCamiloAngelTorrente/JUAN-CAMILO-ANGEL-TORRENTE/blob/main/esqueleto_limpieza_datos2UNIDADCAMILO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Actividad Guiada: Limpieza y Preparación de Datos de Clientes

**Objetivo:** Transformar el archivo `dataset_limpieza_avanzado.csv` en un DataFrame limpio y listo para Machine Learning.

### Punto 1: Importar las Librerías Necesarias
Importa `pandas`, `numpy`, y las clases necesarias de `sklearn` para preprocesamiento (`SimpleImputer`, `LabelEncoder`, `OneHotEncoder`, `MinMaxScaler`, `StandardScaler`).

In [1]:
from google.colab import drive ##Conectar Drive con Colab
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# Tu código aquí
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, MinMaxScaler, StandardScaler

### Punto 2: Cargar el Dataset
Carga el archivo `dataset_limpieza_avanzado.csv` en un DataFrame de pandas llamado `df`.

In [3]:
# Tu código aquí
ruta = '/content/drive/MyDrive/Colab_Notebooks/datasets/dataset_limpieza_avanzadoCAMILO.csv'

# Intento con latin-1
df = pd.read_csv(ruta, encoding='latin-1')

df.head()

   ID_Cliente  Edad    Genero   Ciudad  Ingresos_Anuales Suscrito
0           1   NaN         M     Cali               NaN       no
1           2  52.0      Masc  BogotÃ¡           93039.0       no
2           3  66.0  femenino     cali          119597.0       NO
3           4  68.0      Masc      BOG          122302.0       SI
4           5  41.0      Masc     cali          105000.0       si

### Punto 3: Exploración Inicial
Muestra las primeras 5 filas del DataFrame, su información general (`.info()`) y sus dimensiones (`.shape`).

In [4]:
# Mostrar las primeras 5 filas
print("Primeras 5 filas:")
display(df.head())

# Información general del DataFrame
print("\nInformación general:")
df.info()

# Dimensiones del DataFrame
print("\nDimensiones (filas, columnas):")
print(df.shape)

Primeras 5 filas:

   ID_Cliente  Edad    Genero   Ciudad  Ingresos_Anuales Suscrito
0           1   NaN         M     Cali               NaN       no
1           2  52.0      Masc  BogotÃ¡           93039.0       no
2           3  66.0  femenino     cali          119597.0       NO
3           4  68.0      Masc      BOG          122302.0       SI
4           5  41.0      Masc     cali          105000.0       si

Información general:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID_Cliente        100 non-null    int64
 1   Edad              80 non-null     float64
 2   Genero            90 non-null     object
 3   Ciudad            88 non-null     object
 4   Ingresos_Anuales  83 non-null     float64
 5   Suscrito          100 non-null    object
dtypes: float64(2), int64(1), object(3)
memory usage: 4.8+ KB

Dimensiones (filas, columnas):
(100, 6)

### Punto 4: Conteo de Valores Nulos
Calcula y muestra la cantidad de valores nulos por cada columna.

In [5]:
# Tu código aquí
print("Cantidad de valores nulos por columna:")
df.isnull().sum()

Cantidad de valores nulos por columna:

ID_Cliente           0
Edad                20
Genero              10
Ciudad              12
Ingresos_Anuales    17
Suscrito             0
dtype: int64

La edad y los ingresos anuales se corrigen con la mediana porque son datos númericos

In [6]:
df['Edad'] . fillna(df['Edad']. median(), inplace=True)
df['Ingresos_Anuales'] . fillna(df['Ingresos_Anuales']. median(), inplace=True)
df['Ciudad'] . fillna(df['Ciudad']. mode()[0], inplace=True)
df.isnull().sum()

/tmp/ipython-input-3349411865.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Edad'] . fillna(df['Edad']. median(), inplace=True)
/tmp/ipython-input-3349411865.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Ingresos_Anuales'] . fillna(df['Ingresos_Anuales']. median(), inplace=True)
/tmp/ipython-input-3349411865.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Ciudad'] . fillna(df['Ciudad']. mode()[0], inplace=True)

ID_Cliente           0
Edad                 0
Genero              10
Ciudad               0
Ingresos_Anuales     0
Suscrito             0
dtype: int64

Aquí ya se reemplazaron los datos nulos con la mediana (ingresos y edad) y con la moda (ciudad)

### Punto 5: Analizar Valores Únicos en Columnas Categóricas
Para cada columna categórica (`Genero`, `Ciudad`, `Suscrito`), muestra sus valores únicos para identificar los errores a corregir.

In [7]:
# Tu código aquí
# Columnas categóricas a analizar
columnas_categoricas = ["Genero", "Ciudad", "Suscrito"]

# Mostrar valores únicos en cada columna categórica
for col in columnas_categoricas:
    print(f"\nValores únicos en '{col}':")
    print(df[col].unique())
    print('-'* 40)

Valores únicos en 'Genero':
['M' 'Masc' 'femenino' 'masculino' 'Otro' 'Femenin' 'Femenino' 'Masculino'
 nan]
----------------------------------------

Valores únicos en 'Ciudad':
['Cali' 'BogotÃ¡' 'cali' 'BOG' 'bogota' 'Cartgena' 'Cartagena' 'Medelin'
 'MedellÃ\xadn']
----------------------------------------

Valores únicos en 'Suscrito':
['no' 'NO' 'SI' 'si' 'sI' 'Si' 'No' 'nO']
----------------------------------------

### Punto 6: Estandarizar la Columna 'Genero'
- Convierte todo el texto a minúsculas.
- Corrige los errores tipográficos (ej. 'masc' -> 'masculino', 'femenin' -> 'femenino').
- Muestra los valores únicos de nuevo para verificar la corrección.

In [8]:
# Tu código aquí
# Convertir todo a minúsculas
df["Genero"] = df["Genero"].str.lower()

# Corregir errores tipográficos comunes
df["Genero"] = df["Genero"].replace({
    "masc": "masculino",
    "masculin": "masculino",
    "m": "masculino",
    "fem": "femenino",
    "femenin": "femenino",
    "f": "femenino"
})

# Verificar valores únicos después de la corrección
print("Valores únicos en 'Genero' después de estandarizar:")
print(df["Genero"].unique())

df['Genero'].value_counts()

Valores únicos en 'Genero' después de estandarizar:
['masculino' 'femenino' 'otro' nan]

Genero
masculino    52
femenino     28
otro         10
Name: count, dtype: int64

### Punto 7: Estandarizar la Columna 'Suscrito'
- Unifica los valores a solo dos categorías: 'si' y 'no'.
- Muestra los valores únicos para verificar.

In [9]:
# Tu código aquí
# Pasar todo a minúsculas y quitar espacios extra
df["Suscrito"] = df["Suscrito"].str.lower().str.strip()

# Reemplazar variaciones comunes
df["Suscrito"] = df["Suscrito"].replace({
    "si": "sí",
    "s": "sí",
    "yes": "sí",
    "y": "sí",
    "noo": "no",
    "n": "no"
})

# Verificar valores únicos después de la corrección
print("Valores únicos en 'Suscrito' después de estandarizar:")
print(df["Suscrito"].unique())

Valores únicos en 'Suscrito' después de estandarizar:
['no' 'sí']

In [10]:
df['Suscrito'].value_counts()

Suscrito
sí    55
no    45
Name: count, dtype: int64

### Punto 8: Imputar Valores Nulos en 'Ingresos_Anuales'
Utiliza `SimpleImputer` para reemplazar los valores `NaN` en la columna `Ingresos_Anuales` con la **media** de la columna.

In [11]:
# Tu código aquí
# Ya se reemplazaron los valores nulos con la media en el punto 4 donde se realizó el conteo.

### Punto 9: Imputar Valores Nulos en 'Ciudad'
Utiliza `SimpleImputer` para reemplazar los valores `NaN` en la columna `Ciudad` con la **moda** (el valor más frecuente).

In [12]:
# Tu código aquí - Se reemplazan los datos para que los valores de ciudad sean uniformes
# Ya arriba se normalizaron los datos de ciudad con la MODA
df['Ciudad'] = df['Ciudad'].str.lower() ##Pasa los datos a minuscula
df['Ciudad'] = df['Ciudad'].replace('medelin', 'medellin')
df['Ciudad'] = df['Ciudad'].replace('medellã­n', 'medellin')
df['Ciudad'] = df['Ciudad'].replace('bogotã¡', 'bogota')
df['Ciudad'] = df['Ciudad'].replace('cartgena', 'cartagena')
df['Ciudad'] = df['Ciudad'].replace('bog', 'bogota')
df['Ciudad'].value_counts()

Ciudad
medellin     40
bogota       22
cartagena    21
cali         17
Name: count, dtype: int64

### Punto 10: Aplicar Label Encoding a 'Suscrito'
Usa `LabelEncoder` para transformar la columna `Suscrito` en valores numéricos (0 y 1).

In [13]:
# Tu código aquí
from sklearn.preprocessing import LabelEncoder

# Crear el codificador
encoder = LabelEncoder()

# Aplicar el encoding a la columna 'Suscrito'
df["Suscrito"] = encoder.fit_transform(df["Suscrito"])

# Verificar los valores transformados
print("Valores únicos en 'Suscrito' después del Label Encoding:")
print(df["Suscrito"].unique())

# Mostrar cómo quedó el mapeo
print("\nMapeo de valores:")
for original, encoded in zip(encoder.classes_, encoder.transform(encoder.classes_)):
    print(f"{original} -> {encoded}")

Valores únicos en 'Suscrito' después del Label Encoding:
[0 1]

Mapeo de valores:
no -> 0
sí -> 1

### Punto 11: Aplicar One-Hot Encoding a 'Genero'
- Utiliza `pd.get_dummies()` para crear nuevas columnas para cada categoría de 'Genero'.
- Une estas nuevas columnas al DataFrame principal y elimina la columna 'Genero' original.

In [14]:
# Tu código aquí
# Crear variables dummies para la columna 'Genero'
dummies_genero = pd.get_dummies(df['Genero'], prefix='Genero')

# Unir las variables dummies al DataFrame principal
df = pd.concat([df, dummies_genero], axis=1)

# Eliminar la columna original 'Genero'
df = df.drop('Genero', axis=1)

# Mostrar el DataFrame actualizado
df.head()

,ID_Cliente,Edad,Ciudad,Ingresos_Anuales,Suscrito,Genero_femenino,Genero_masculino,Genero_otro
0,1,46.0,cali,92147.0,0,False,True,False
1,2,52.0,bogota,93039.0,0,False,True,False
2,3,66.0,cali,119597.0,0,True,False,False
3,4,68.0,bogota,122302.0,1,False,True,False
4,5,41.0,cali,105000.0,1,False,True,False

### Punto 12: Imputación Final y Verificación
- La columna 'Edad' aún tiene nulos. Imputa sus valores usando la **mediana**.
- Después de todas las imputaciones, ejecuta de nuevo el conteo de valores nulos para asegurarte de que no queda ninguno.

In [15]:
# Tu código aquí
# Ya se reemplazaron los valores nulos con la mediana en el punto 4 donde se realizó el conteo.

### Punto 13: Normalización (Min-Max Scaling)
Aplica `MinMaxScaler` a la columna `Ingresos_Anuales` para escalar sus valores al rango [0, 1].

In [16]:
# Tu código aquí
from sklearn.preprocessing import MinMaxScaler

# Crear el escalador
scaler = MinMaxScaler()

# Aplicar Min-Max Scaling a la columna 'Ingresos_Anuales'
df['Ingresos_Anuales_Normalizados'] = scaler.fit_transform(df[['Ingresos_Anuales']])

# Mostrar el DataFrame actualizado
df.head()

,ID_Cliente,Edad,Ciudad,Ingresos_Anuales,Suscrito,Genero_femenino,Genero_masculino,Genero_otro,Ingresos_Anuales_Normalizados
0,1,46.0,cali,92147.0,0,False,True,False,0.519278
1,2,52.0,bogota,93039.0,0,False,True,False,0.526882
2,3,66.0,cali,119597.0,0,True,False,False,0.753271
3,4,68.0,bogota,122302.0,1,False,True,False,0.776330
4,5,41.0,cali,105000.0,1,False,True,False,0.628841

### Punto 14: Estandarización (Standard Scaler)
Aplica `StandardScaler` a la columna `Edad` para que tenga una media de 0 y una desviación estándar de 1.

In [17]:
# Tu código aquí
from sklearn.preprocessing import StandardScaler

# Crear el escalador
scaler = StandardScaler()

# Aplicar StandardScaler a la columna 'Edad'
df['Edad_Estandarizada'] = scaler.fit_transform(df[['Edad']])

# Mostrar el DataFrame actualizado
df.head()

,ID_Cliente,Edad,Ciudad,Ingresos_Anuales,Suscrito,Genero_femenino,Genero_masculino,Genero_otro,Ingresos_Anuales_Normalizados,Edad_Estandarizada
0,1,46.0,cali,92147.0,0,False,True,False,0.519278,0.071133
1,2,52.0,bogota,93039.0,0,False,True,False,0.526882,0.477610
2,3,66.0,cali,119597.0,0,True,False,False,0.753271,1.426054
3,4,68.0,bogota,122302.0,1,False,True,False,0.776330,1.561546
4,5,41.0,cali,105000.0,1,False,True,False,0.628841,-0.267597

### Punto 15: Revisión Final del Dataset
- Muestra las primeras 5 filas del DataFrame final.
- Muestra la información (`.info()`) para confirmar que todas las columnas son numéricas y no hay nulos.
- ¡Felicidades, el dataset está limpio y listo!

In [18]:
# Tu código aquí
# Mostrar las primeras 5 filas del DataFrame final
print("Primeras 5 filas del DataFrame final:")
display(df.head())

# Mostrar la información general del DataFrame
print("\nInformación del DataFrame final:")
df.info()

Primeras 5 filas del DataFrame final:

,ID_Cliente,Edad,Ciudad,Ingresos_Anuales,Suscrito,Genero_femenino,Genero_masculino,Genero_otro,Ingresos_Anuales_Normalizados,Edad_Estandarizada
0,1,46.0,cali,92147.0,0,False,True,False,0.519278,0.071133
1,2,52.0,bogota,93039.0,0,False,True,False,0.526882,0.477610
2,3,66.0,cali,119597.0,0,True,False,False,0.753271,1.426054
3,4,68.0,bogota,122302.0,1,False,True,False,0.776330,1.561546
4,5,41.0,cali,105000.0,1,False,True,False,0.628841,-0.267597

Información del DataFrame final:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   ID_Cliente                     100 non-null    int64
 1   Edad                           100 non-null    float64
 2   Ciudad                         100 non-null    object
 3   Ingresos_Anuales               100 non-null    float64
 4   Suscrito                       100 non-null    int64
 5   Genero_femenino                100 non-null    bool
 6   Genero_masculino               100 non-null    bool
 7   Genero_otro                    100 non-null    bool
 8   Ingresos_Anuales_Normalizados  100 non-null    float64
 9   Edad_Estandarizada             100 non-null    float64
dtypes: bool(3), float64(4), int64(2), object(1)
memory usage: 5.9+ KB

In [19]:
df.describe()

,ID_Cliente,Edad,Ingresos_Anuales,Suscrito,Ingresos_Anuales_Normalizados,Edad_Estandarizada
count,100.000000,100.000000,100.000000,100.00,100.000000,1.000000e+02
mean,50.500000,44.950000,88801.310000,0.55,0.490758,-1.879052e-16
std,29.011492,14.835376,34030.018585,0.50,0.290084,1.005038e+00
min,1.000000,18.000000,31230.000000,0.00,0.000000,-1.825755e+00
25%,25.750000,33.750000,57921.750000,0.00,0.227530,-7.587555e-01
50%,50.500000,46.000000,92147.000000,1.00,0.519278,7.113333e-02
75%,75.250000,57.000000,119180.000000,1.00,0.749717,8.163396e-01
max,100.000000,70.000000,148541.000000,1.00,1.000000,1.697038e+00